INSERT INTO `devwave`.`random_sentence` (`sentence`) VALUES
( 'Vote pour ton banger actuel'),
( 'Qui a besoin d''une baguette magique quand tu peux faire de la magie en votant pour ta musique préférée ? Allez, abracadabra'),
( 'Donne à ta musique préférée une étreinte bien méritée !'),
( 'La musique est une langue universelle, et ton vote compte comme un mot d''amour. Fais entendre ta voix !'),
( 'Besoin d''un groove dans ta journée ? Vote pour ta musique préférée et laisse la magie opérer'),
( 'Un vote pour ta musique préférée, c''est comme un high-five à ton oreille. Allez, tape-la !'),
( 'Tu veux que ta musique passe à Couleur 3 ? Oublie pas de voter !'),
( 'Fais-nous découvrir ton banger du moment !'),
( 'Quelle musique pour l’apéro de ce soir ?'),
( 'Vote pour ta musique préférée et fais danser ton cœur!'),
( 'Un vote pour ta chanson préférée, c''est un sourire dans les oreilles!'),
( 'Ta musique préférée mérite ton vote. Laisse-la briller !'),
( 'T’es pas allez voter aux dernières votations ? Rattrapes toi dans notre application'),
( 'Pas de temps à perdre, vote pour ta chanson préférée maintenant !'),
( 'Ne garde pas ta musique préférée pour toi, partage-la avec nous !'),
( 'T’as du bon son dans ta valise musicale ? Donne-nous l’adresse'),
( 'Ne garde pas ton banger que pour toi, met le sur le grill'),
( 'Tant de belles musiques inconnues, aide-nous à diversifier notre playlist !');
